# Generated by Django 5.2.10 on 2026-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentperformance",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
